name: Run Node.js Script

on:
  push:
    branches:
      - main
      - master

jobs:
  run-node-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run Node.js script
        run: node main.js
